### PR TITLE
Adding information regarding enode order in static-nodes.json

### PR DESCRIPTION
**Pull request by coeniebeyers**

### CODE REVIEW

**Comment by bts** [comment]
Thanks Coenie! I think we need to change `need` to `needs` (`the order ... needs`) but other than that, looks good to me.

**Comment by bts** [comment]
Thanks.

@patrickmn can you merge this when you have a chance?

**Comment by patrickmn** [comment]
@coeniebeyers Please execute the CLA (which is required even for small changes): https://github.com/jpmorganchase/cla

**Comment by coeniebeyers** [comment]
Had to track down a printer/scanner :) Sent the signed CLA.

**Comment by patrickmn** [comment]
Received -- thanks Coenie!

**Review by patrickmn — APPROVED** [review]

**Pull request merged**
