### PR TITLE
Send raft pending logs events on any subscribed channels.

### LINKED ISSUE #1156: [Raft] Pending logs events no longer being handled
#### System information

Current `master` branch

```shell
 ~/Work/quorum-examples/examples/7nodes % geth version
Geth
Version: 1.9.20-stable
Git Commit: eb8f6bf522629bac2eba2e39474fa169753ca712
Git Commit Date: 20210326
Quorum Version: 21.1.0
```

#### Issue
#1121 introduced https://github.com/ethereum/go-ethereum/pull/20312/ which switches from `event.TypeMux` to an `event.Feed` subscription for sending pending logs events to the `filters` package.

`raft.minter::firePendingBlockEvents` still sends these events on the `event.TypeMux` and as a result the `filters` package is not handling them.

#### Steps to reproduce the behaviour
This can be observed by subscribing to `logs` events on a websockets-enabled leader node using something like `wscat`, e.g.:  

```shell
~/Work/quorum-examples/examples/7nodes % wscat -c ws://localhost:23004
Connected (press CTRL+C to quit)

> {"id":1, "method":"eth_subscribe", "params":["logs", {"FromBlock":"pending","ToBlock":"pending"}]}
```

When sending transactions that emit logs, no events are returned by the subscription.

### PR DESCRIPTION
**Pull request by chris-j-h**
Fixes #1156

### CODE REVIEW

**Comment by ricardolyn** [comment]
@chris-j-h what Unit or Acceptance Test do you recommend for capturing this regression in the future?

**Comment by chris-j-h** [comment]
@ricardolyn added some unit tests to verify the eth service and raft service sides

**Comment by ricardolyn** [comment]
@chris-j-h thank you! so it can capture a future regression

**Review by ricardolyn — APPROVED** [review]
LGTM. thank you

**Comment by nmvalera** [comment]
@chris-j-h Q: do we need to do something similar for other type of events such `NewChainHead`, etc.?

**Comment by chris-j-h** [comment]
@nmvalera the `eventMux` is still used for other events.  The other event subscription in the `filters` pkg moved away from `eventMux` a long time ago (quorum v2.2.2).  The pending logs subscription was the only one remaining.

**Pull request merged**
