### PR TITLE
Fix TestUpdatedKeyfileContents, TestEIP155SigningVitalik and TestChainId

### PR DESCRIPTION
**Pull request by tsuzukit**
For fixing `TestUpdatedKeyfileContents`, I have cherry-picked https://github.com/jpmorganchase/quorum/commit/c86c12696db61511e7983d922505f59e7ddac076 and https://github.com/jpmorganchase/quorum/commit/c8b5da70df05f7ce7f05180f87f8429a2cff4d23 which are already merged to geth 1.7.3.

For fixing `TestEIP155SigningVitalik`, I needed to change `chainId` to something other than `1` as it results in `V` of `37` and Tx is treated as protected transaction in Quorum (https://github.com/jpmorganchase/quorum/blob/master/core/types/transaction.go#L138).
Since http://vitalik.ca/files/eip155_testvec.txt is not currently accessible, I just created some tx and address pair. (tx creation rules are written in comments)

For same reason, I needed to change `chainId` for `TestChainId`.

Please review.

### CODE REVIEW

**Comment by jpmsam** [comment]
@tsuzukit Thank you for this, we'll be reviewing the changes and EIP155. In the meantime, please complete our [CLA](https://github.com/jpmorganchase/cla/blob/master/README.md)

**Comment by tsuzukit** [comment]
@jpmsam 
Hi, thank you for the response and review! 
I have sent CLA to quorum_cla@jpmorgan.com.

**Comment by nujabes403** [comment]
Please merge this request quickly.. 'Invalid sender' error is critical for further developing..

**Comment by jpmsam** [comment]
@nujabes403 we are working on testing it. Please provide your feedback on whether the updates fixed the issue for you as well.

**Comment by tsuzukit** [comment]
Actually, https://github.com/jpmorganchase/quorum/pull/350 is the fix to "invalid sender".
This pull request is intended to fix some unit tests.

**Comment by jpmsam** [comment]
@tsuzukit thanks, we are in the process of testing both.

**Comment by xiaods** [comment]
the master branch it test failing in macos, please review and merge it asap.

**Review by jpmsam — APPROVED** [review]

**Pull request merged**
