### PR TITLE
Bugfix/geth console displays incorrect block timestamp

### LINKED ISSUE #698: Raft consensus: geth console displays incorrect block timestamp
#### System information

Version: 1.8.18-stable
Git Commit: 2d22fd0044a9370d0e3f97227354b2fb644586df
Quorum Version: 2.2.3
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1337
Go Version: go1.10.4
Operating System: darwin

#### Description

When 'geth console' is executed, the console displays the timestamp of the latest block, e.g.:
```
Welcome to the Geth JavaScript console!

instance: Geth/v1.8.18-stable-2d22fd00(quorum-v2.2.3)/darwin-amd64/go1.10.4
coinbase: 0xed9d02e382b34818e88b88a309c7fe71e65f419d
at block: 5 (Fri, 28 Nov 49325133006 11:29:03 GMT)
```

As you can see, the timestamp is incorrect in the year.
This is because the console expects the block timestamp to be in seconds, but for Raft it is held in nanoseconds.
The relevant code is in console.console.go::Welcome(), where it has the code:
```
console.log("at block: " + eth.blockNumber + " (" + new Date(1000 * eth.getBlock(eth.blockNumber).timestamp) + ")");
```
Under Raft, this code should be:
```
console.log("at block: " + eth.blockNumber + " (" + new Date(eth.getBlock(eth.blockNumber).timestamp / 1000000) + ")");
```
However, I don't know how we could tell in the console that Raft consensus is being used.

### PR DESCRIPTION
**Pull request by SatpalSandhu61**
Fixes #698 where geth console displays incorrect timestamp under Raft, due to Raft holding block timestamp in nanoseconds, instead of seconds.
This PR incorporates review comments and adds unit test.

### CODE REVIEW

**Review by trung — APPROVED** [review]
LGTM

**Review by fixanoid — APPROVED** [review]

**Review by jbhurat — APPROVED** [review]
LGTM

**Comment by sinornis** [comment]
good

**Review by sinornis — APPROVED** [review]
usefull

**Pull request merged**
