### PR TITLE
consensus, core, eth, miner, params: update istanbul engine

### PR DESCRIPTION
**Pull request by markya0616**
Update istanbul engine. 
1. Marshal/Unmarshal snapshot 
2. Performance improvement

### CODE REVIEW

**Comment by stevenroose** [comment]
Is this change compatible with existing Istanbul setups? I tried to run this with my existing Istanbul blockchain, and all validators seem to stop making blocks :)

**Comment by markya0616** [comment]
Yes, it should be. Do you start it with `--syncmode "full"` flag? We've already slacked you, and please provide more logs to us. :)

**Comment by stevenroose** [comment]
It did work when I started from scratch (with 7 nodes instead of 3).

**Comment by yutelin** [comment]
@tylobban @joelburget @patrickmn Can you take a look? Thanks!

**Comment by patrickmn** [comment]
So does this have backwards compatibility issues or not?

**Comment by yutelin** [comment]
@patrickmn This PR was to add back the missing code from our original PR (https://github.com/jpmorganchase/quorum/pull/166). It contains some fixes as well as performance improvement.

**Review by patrickmn — APPROVED** [review]

**Pull request merged**
