### PR TITLE
Quorum raft upgrade v3.3.13

### PR DESCRIPTION
**Pull request by vsmk98**
This PR contains the following changes to Raft consensus:

- Upgrade quorum's Raft library to version v3.3.13 from upstream.
- Raft API to add raft learner node in quorum. learner node will follow the leader but will not vote or take part in quorum for commits.
- Raft API for promoting a learner node to peer node
- Disallow learner node from adding another learner or peer 
- Disallow learner node from promoting itself or other learners to peer
- Disallow learner node to remove other peers or learners from raft cluster
- Allow learner node to remove itself from raft cluster

#825, #790, #852, #180

### CODE REVIEW

**Comment by lookfwd** [comment]
Wondering how has this been tested?

**Comment by amalrajmani** [comment]
> Wondering how has this been tested?

When a new node joins the network as a peer, it tries to sync with leader and during this time the leader is overloaded and can potentially lead to periods of cluster unavailability. Please refer to https://github.com/etcd-io/etcd/blob/master/Documentation/learning/design-learner.md  for further details on various scenarios. The advantage of a learner node is it joins the network as a non voting member and hence does not impact the Raft quorum.
For testing this, brought up a 3 node raft network and created few thousand blocks. Then added a 4th node as peer. While the 4th node is syncing with the network, brought down one of the other nodes. Now if any transaction is send, the transaction will wait till the newly joined node is fully synced with the network.
Repeated the same test adding the 4th node as learner. In this case the network will be able to process the transactions while the new learner node is still syncing with the network

**Review by jbhurat — COMMENTED** [review]
When a node is learner and it calls `raft.removePeer()` on itself, it returns null. When checking `raft.cluster` the node is still seen with a **`verifier`** role. Running `raft.role` returns an empty string. Running `raft.cluster` from any other node returns correct results though

**Review by jbhurat — DISMISSED** [review]
LGTM

**Comment by amalrajmani** [comment]
> When a node is learner and it calls `raft.removePeer()` on itself, it returns null. When checking `raft.cluster` the node is still seen with a **`verifier`** role. Running `raft.role` returns an empty string. Running `raft.cluster` from any other node returns correct results though

this has been fixed now. after a learner/peer node removes itself it will return an empty array when `raft.cluster` is called

**Review by trung — APPROVED** [review]
LGTM. Changes in the original etcd raft library:
- Inject a channel to capture role change: `roleC`
- Populate `ConfState` to separate voters and learners, similar to [raft: raft learners should be returned after applyConfChange by absolute8511 · Pull Request #9116 · etcd-io/etcd](https://github.com/etcd-io/etcd/pull/9116/files)

**Review by jpmsam — APPROVED** [review]

**Pull request merged**
