### PR TITLE
Set tcp port of p2p node by raft peer correctly.

### PR DESCRIPTION
**Pull request by henryfour**
Fix problems like below:
```
TRACE[07-12|02:00:16.844] New dial task task="staticdial 7577115fd9184a27 127.0.0.1:0"
TRACE[07-12|02:00:16.844] Dial error task="staticdial 7577115fd9184a27 127.0.0.1:0"  err="dial tcp 127.0.0.1:0: getsockopt: connection refused"
```
The problem can be reproduced by restarting multiple raft nodes with **--raftjoinexisting id** whose **static-nodes.json** is deleted.
It arised because the TCP port of the static node is not set correctly by raft ProtocolManager.

### CODE REVIEW

**Review by sinornis — APPROVED** [review]
good, usefull to me

**Comment by fixanoid** [comment]
Hi @henryfour thanks for the contribution. Before we can accept the changes, we require developers to sign and submit this CLA: https://github.com/jpmorganchase/cla. Thank you.

**Review by jpmsam — APPROVED** [review]

**Review by prd-fox — APPROVED** [review]

**Comment by henryfour** [comment]
@fixanoid : FYI, the signed CLA was emailed a moment ago

**Comment by fixanoid** [comment]
CLA received.

**Comment by robinbryce** [comment]
This bug also prevented nodes declared in static-nodes.json from getting re-connected after network connectivity is lost and later restored. Thanks *very* much for the fix

**Pull request merged**
