### PR TITLE
Increase RPC server buffer size to 128kb

### PR DESCRIPTION
**Pull request by vdamle**
Changes in #636 makes transaction size limit configurable up to a maximum of 128kb.
RPC server creates a buffer to accept payload for a transaction, this
change increases the size of the buffer to 128kb to match the maximum
allowed in chain config

### CODE REVIEW

**Comment by fixanoid** [comment]
Hi @vdamle, thanks for the PR. Would you be able to fill in our CLA before we merge it? Thank you.

CLA: https://github.com/jpmorganchase/cla

**Comment by fixanoid** [comment]
Hi @vdamle, thanks for the PR. Would you be able to fill in our CLA before we merge it? Thank you.

CLA: https://github.com/jpmorganchase/cla

**Comment by vdamle** [comment]
sorry @fixanoid , had not seen your comment. Will submit a CLA shortly

**Comment by vdamle** [comment]
FYI @fixanoid : Emailed a signed CLA a moment ago

**Review by fixanoid — APPROVED** [review]

**Comment by fixanoid** [comment]
CLA received. Thank you!

**Review by jpmsam — APPROVED** [review]

**Pull request merged**
