### PR TITLE
Removed docs files now included in doc.goquorum and doc.tessera repos

### PR DESCRIPTION
**Pull request by MadelineMurray**
Quorum and Tessera docs are now included in the doc.goquorum and doc.tessera repos (will be made public later today).  The content previously included in the deleted files is now included in those repos so these files can be removed from this repo.  The docs sites https://docs.goquorum.consensys.net and https://docs.tessera.consensys.net are publishing from the doc.goquorum and doc.tessera repos. 

@jpmsam - let me know if you've got any questions about this.

### CODE REVIEW

**Comment by jpmsam** [comment]
@MadelineMurray it's a good idea to have this separation. We'll check the new repos for docs before we remove it completely from this repo but all new PRs will go in docs.quorum||tessera.

**Comment by MadelineMurray** [comment]
@jpmsam - thanks.  It'll be good to have you look at the new repos. Not sure if you've looked at the new docs sites but the structure has been updated to matched the other ConsenSys Quorum products.  The content is split at the top level into How To/Concepts/Tutorials/Reference.  Let me know if you can't find anything specific.  

I'll tag you later once I've got the docs repo public.

**Comment by jpmsam** [comment]
@MadelineMurray I reviewed the docs and the structure wasn't very clear to me initially but I understand trying to maintain the same format as all the other Consensys Quorum products. 

Thank you for working on making the repos public!

**Comment by MadelineMurray** [comment]
@jpmsam - this explains the concept behind how the docs are structured - https://documentation.divio.com/ 

The TL;DR 
* Concepts and Tutorials are content for new users or existing users trying to understand a feature they haven't used more 
* How To and Reference content is for users that are familiar with what they're doing but need to refer to the docs to retrieve the details of something specific

**Comment by MadelineMurray** [comment]
The new docs repos are public now: 
https://github.com/ConsenSys/doc.goquorum 
https://github.com/ConsenSys/doc.tessera

**Comment by jpmsam** [comment]
Thanks @MadelineMurray the team is looking at some of the missing documentation that wasn't included in the new repos.

**Review by NicolasMassart — APPROVED** [review]
Looks good to me.

**Review by jpmsam — APPROVED** [review]

**Pull request merged**
